"""sqft fields on lot_assignments and pallets

Revision ID: 3c6b3348c600
Revises: b9f24bef22fe
Create Date: 2026-05-15 15:29:17.692480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6b3348c600'
down_revision: Union[str, Sequence[str], None] = 'b9f24bef22fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable, backfill, then set NOT NULL to avoid violating existing rows.
    op.add_column('lot_assignments', sa.Column('planned_sqft', sa.Float(), nullable=True, server_default='0'))
    op.add_column('lot_assignments', sa.Column('actual_sqft', sa.Float(), nullable=True, server_default='0'))
    op.add_column('pallets', sa.Column('sqft', sa.Float(), nullable=True, server_default='0'))
    op.execute("UPDATE lot_assignments SET planned_sqft = 0 WHERE planned_sqft IS NULL")
    op.execute("UPDATE lot_assignments SET actual_sqft = 0 WHERE actual_sqft IS NULL")
    op.execute("UPDATE pallets SET sqft = 0 WHERE sqft IS NULL")
    op.alter_column('lot_assignments', 'planned_sqft', nullable=False, server_default=None)
    op.alter_column('lot_assignments', 'actual_sqft', nullable=False, server_default=None)
    op.alter_column('pallets', 'sqft', nullable=False, server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pallets', 'sqft')
    op.drop_column('lot_assignments', 'actual_sqft')
    op.drop_column('lot_assignments', 'planned_sqft')
    # ### end Alembic commands ###
