"""add sku_id to lot_assignments

Revision ID: 979d959b2156
Revises: e2ed3602fc4e
Create Date: 2026-05-15 12:01:11.147524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979d959b2156'
down_revision: Union[str, Sequence[str], None] = 'e2ed3602fc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot_assignments', sa.Column('sku_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lot_assignments_sku_id'), 'lot_assignments', ['sku_id'], unique=False)
    op.create_foreign_key(None, 'lot_assignments', 'skus', ['sku_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lot_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_lot_assignments_sku_id'), table_name='lot_assignments')
    op.drop_column('lot_assignments', 'sku_id')
    # ### end Alembic commands ###
