"""container packaging fields

Revision ID: b9f24bef22fe
Revises: c5b4ddff7896
Create Date: 2026-05-15 14:54:52.055294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f24bef22fe'
down_revision: Union[str, Sequence[str], None] = 'c5b4ddff7896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('on_pallet', sa.Boolean(), nullable=True))
    op.add_column('containers', sa.Column('pallet_length_in', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('pallet_width_in', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('item_length_in', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('item_width_in', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('item_height_in', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'item_height_in')
    op.drop_column('containers', 'item_width_in')
    op.drop_column('containers', 'item_length_in')
    op.drop_column('containers', 'pallet_width_in')
    op.drop_column('containers', 'pallet_length_in')
    op.drop_column('containers', 'on_pallet')
    # ### end Alembic commands ###
