"""add grid coords to lots

Revision ID: c5b4ddff7896
Revises: 979d959b2156
Create Date: 2026-05-15 13:03:41.316190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b4ddff7896'
down_revision: Union[str, Sequence[str], None] = '979d959b2156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('grid_row', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('grid_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'grid_col')
    op.drop_column('lots', 'grid_row')
    # ### end Alembic commands ###
