"""whpo driver info fields

Revision ID: de310e4a215b
Revises: f0bf04d3f58b
Create Date: 2026-05-16 13:25:51.742973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de310e4a215b'
down_revision: Union[str, Sequence[str], None] = 'f0bf04d3f58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whpos', sa.Column('driver_name', sa.String(length=120), nullable=True))
    op.add_column('whpos', sa.Column('driver_license', sa.String(length=60), nullable=True))
    op.add_column('whpos', sa.Column('truck_license_plate', sa.String(length=20), nullable=True))
    op.add_column('whpos', sa.Column('insurance', sa.Text(), nullable=True))
    op.add_column('whpos', sa.Column('driver_info_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whpos', 'driver_info_received_at')
    op.drop_column('whpos', 'insurance')
    op.drop_column('whpos', 'truck_license_plate')
    op.drop_column('whpos', 'driver_license')
    op.drop_column('whpos', 'driver_name')
    # ### end Alembic commands ###
