"""initial schema

Revision ID: e2ed3602fc4e
Revises: 
Create Date: 2026-05-15 11:57:08.987193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2ed3602fc4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_kind'), 'activity_log', ['kind'], unique=False)
    op.create_index(op.f('ix_activity_log_t'), 'activity_log', ['t'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_by', sa.String(length=80), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=80), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_kind'), 'exceptions', ['kind'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('layout', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('sqft_capacity', sa.Float(), nullable=False),
    sa.Column('pallet_capacity', sa.Integer(), nullable=False),
    sa.Column('max_stack_levels', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'lot_code', name='uq_lots_floor_code')
    )
    op.create_index(op.f('ix_lots_floor_id'), 'lots', ['floor_id'], unique=False)
    op.create_index(op.f('ix_lots_lot_code'), 'lots', ['lot_code'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sqft_per_unit', sa.Float(), nullable=True),
    sa.Column('items_per_pallet', sa.Integer(), nullable=True),
    sa.Column('pallet_mode', sa.String(length=16), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack_height', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'sku', name='uq_skus_customer_sku')
    )
    op.create_index(op.f('ix_skus_customer_id'), 'skus', ['customer_id'], unique=False)
    op.create_index(op.f('ix_skus_sku'), 'skus', ['sku'], unique=False)
    op.create_table('whpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whpo_number', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whpos_customer_id'), 'whpos', ['customer_id'], unique=False)
    op.create_index(op.f('ix_whpos_whpo_number'), 'whpos', ['whpo_number'], unique=True)
    op.create_table('dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('do_number', sa.String(length=40), nullable=False),
    sa.Column('whpo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival_time', sa.Time(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['whpo_id'], ['whpos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dos_do_number'), 'dos', ['do_number'], unique=True)
    op.create_index(op.f('ix_dos_status'), 'dos', ['status'], unique=False)
    op.create_index(op.f('ix_dos_whpo_id'), 'dos', ['whpo_id'], unique=True)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_no', sa.String(length=20), nullable=False),
    sa.Column('do_id', sa.Integer(), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('actual_arrival_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.String(length=80), nullable=True),
    sa.Column('finished_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['do_id'], ['dos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_container_no'), 'containers', ['container_no'], unique=True)
    op.create_index(op.f('ix_containers_do_id'), 'containers', ['do_id'], unique=False)
    op.create_index(op.f('ix_containers_status'), 'containers', ['status'], unique=False)
    op.create_table('container_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_raw', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_lines_container_id'), 'container_lines', ['container_id'], unique=False)
    op.create_index(op.f('ix_container_lines_sku_id'), 'container_lines', ['sku_id'], unique=False)
    op.create_table('lot_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('assignment_order', sa.Integer(), nullable=False),
    sa.Column('planned_pallets', sa.Integer(), nullable=False),
    sa.Column('actual_pallets', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'assignment_order', name='uq_lot_assignment_order')
    )
    op.create_index(op.f('ix_lot_assignments_container_id'), 'lot_assignments', ['container_id'], unique=False)
    op.create_index(op.f('ix_lot_assignments_lot_id'), 'lot_assignments', ['lot_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.String(length=80), nullable=False),
    sa.Column('finished_by', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_container_id'), 'receipts', ['container_id'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_table('pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('pallet_mode_at_receipt', sa.String(length=16), nullable=False),
    sa.Column('palletized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('palletized_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallets_container_id'), 'pallets', ['container_id'], unique=False)
    op.create_index(op.f('ix_pallets_lot_id'), 'pallets', ['lot_id'], unique=False)
    op.create_index(op.f('ix_pallets_receipt_id'), 'pallets', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_pallets_sku_id'), 'pallets', ['sku_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('pallet_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('item_barcode', sa.String(length=120), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scanned_by', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_container_id'), 'scans', ['container_id'], unique=False)
    op.create_index(op.f('ix_scans_item_barcode'), 'scans', ['item_barcode'], unique=False)
    op.create_index(op.f('ix_scans_pallet_id'), 'scans', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_scans_receipt_id'), 'scans', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_receipt_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_pallet_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_item_barcode'), table_name='scans')
    op.drop_index(op.f('ix_scans_container_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_pallets_sku_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_receipt_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_lot_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_container_id'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_container_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_lot_assignments_lot_id'), table_name='lot_assignments')
    op.drop_index(op.f('ix_lot_assignments_container_id'), table_name='lot_assignments')
    op.drop_table('lot_assignments')
    op.drop_index(op.f('ix_container_lines_sku_id'), table_name='container_lines')
    op.drop_index(op.f('ix_container_lines_container_id'), table_name='container_lines')
    op.drop_table('container_lines')
    op.drop_index(op.f('ix_containers_status'), table_name='containers')
    op.drop_index(op.f('ix_containers_do_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_no'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_dos_whpo_id'), table_name='dos')
    op.drop_index(op.f('ix_dos_status'), table_name='dos')
    op.drop_index(op.f('ix_dos_do_number'), table_name='dos')
    op.drop_table('dos')
    op.drop_index(op.f('ix_whpos_whpo_number'), table_name='whpos')
    op.drop_index(op.f('ix_whpos_customer_id'), table_name='whpos')
    op.drop_table('whpos')
    op.drop_index(op.f('ix_skus_sku'), table_name='skus')
    op.drop_index(op.f('ix_skus_customer_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_lots_lot_code'), table_name='lots')
    op.drop_index(op.f('ix_lots_floor_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('floors')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_kind'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_activity_log_t'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_kind'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
