"""container arrival time and line product type

Revision ID: f0bf04d3f58b
Revises: 3c6b3348c600
Create Date: 2026-05-15 16:15:40.525097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bf04d3f58b'
down_revision: Union[str, Sequence[str], None] = '3c6b3348c600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_lines', sa.Column('product_type', sa.String(length=120), nullable=True))
    op.add_column('containers', sa.Column('expected_arrival_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'expected_arrival_time')
    op.drop_column('container_lines', 'product_type')
    # ### end Alembic commands ###
